config/routes.rb
Rails.application.routes.draw do
  root 'people#index'

  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  def index
    @people = Person.all
  end

  def show
  end
  def new
    @person = Person.new
  end
  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to people_path
    else
      render :new
    end

  end
  def edit

  end
  def update
    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      render :edit
    end

  end
  def destroy
    @person.destroy
    redirect_to people_path

  end

  private
  def set_person
    @person = Person.find(params[:id])
  end
  def person_params
    params.require(:person).permit(:first_name, :last_name, :email, :avatar, :phone)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_navbar.html.erb
<div class="ui three item menu">
  <%= link_to "People", people_path, class: "item" %>
  <%= link_to "Add Person", new_person_path, class: "item" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

    <body>
      <%= render partial: 'layouts/navbar' %>
      <div class="ui container">
      <%= yield %>
      </div>

      <%# Footer %>
    </body>
  </html>

app/views/people/_form.html.erb
<%= form_with(model: @person, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, palceholders: "firstname", autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, palceholders: "last name", autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :avatar %>
    <%= f.text_field :avatar, required: true, palceholders: "avatar", autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone, required: false, palceholders: "phone", autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, required: true, palceholders: "email", autofocus: true %>
  </div>
  <br>
  <%= f.submit nil, class: "ui button green" %>
  <br>
  <% end  %>
  <br>

app/views/people/edit.html.erb
<h1>edit person</h1>

<%=  render 'form', person: @person %>

<%= link_to "back", people_path %> |
<%= link_to "back", person_path(@person) %>

app/views/people/index.html.erb
<h1 class="ui header">People</h1>
<%= link_to 'New Person', new_person_path %>
<div class="ui divider"></div>

<div class="ui grid">
  <% @people.each do |person| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card">
        <div class="image">
          <img src="https://robohash.org/<%= person.avatar %>?set=set4" />
        </div>
        <div class="content">
          <%= link_to "#{person.first_name} #{person.last_name}", person, class: "header" %>
        </div>
        <div class="extra content">
          <div class="ui two buttons">
            <%= link_to(edit_person_path(person)) %>
            <div class="ui basic green button">
            edit
            </div>

            <%= link_to 'destroy', person, method: :delete, data: {confirm: 'are you sure?'} %>
            <div class="ui basic red button">
              delete
              </div>

            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>

</div>

app/views/people/new.html.erb
<h1>new person</h1>

<%=  render partial: 'form', person: @person %>

<%= link_to "back", people_path %>

app/views/people/show.html.erb
<div class="ui card">
  <div class="image">
    <img src="https://robohash.org/<%= @person.avatar %>?set=set4" />
  </div>
  <div class="content">
    <p class="header">
      <%= @person.first_name %> <%= @person.last_name %>
    </p>
    <div class="meta">
      <span class="date"> <%= @person.phone %></span>
    </div>
    <div class="discription">
      <%= @person.email %>
    </div>
    <div class="extra content">
      <%= link_to "edit", edit_person_path(@person), class: "ui button blue" %> |
      <%= link_to "back", people_path, class: "ui button" %>
    </div>
  </div>

</div>